# Generated by Django 6.1 on 2026-08-24 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('identificador', models.CharField(help_text='Identificador o serie del dispositivo usado por su SDK/API.', max_length=50, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_biometricos', to='core.plantel')),
            ],
            options={
                'verbose_name': 'Dispositivo biométrico',
                'verbose_name_plural': 'Dispositivos biométricos',
                'ordering': ['plantel', 'ubicacion'],
            },
        ),
        migrations.CreateModel(
            name='ParametroGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('intervalo_minutos', models.PositiveSmallIntegerField(default=5)),
                ('plantel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_gps', to='core.plantel')),
            ],
            options={
                'verbose_name': 'Parámetro de GPS',
                'verbose_name_plural': 'Parámetros de GPS',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('origen', models.CharField(choices=[('BIOMETRICO', 'Biométrico'), ('MANUAL', 'Manual')], default='BIOMETRICO', max_length=10)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='asistencia.dispositivobiometrico')),
                ('persona', models.ForeignKey(limit_choices_to={'rol_principal__in': ['ALUMNO', 'DOCENTE']}, on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario administrativo que capturó el registro manual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_asistencia_capturados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dentro_del_plantel', models.BooleanField(default=False, help_text='Calculado por el backend al recibir el reporte (geocerca del plantel).')),
                ('persona', models.ForeignKey(limit_choices_to={'rol_principal__in': ['ALUMNO', 'DOCENTE']}, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_gps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación GPS',
                'verbose_name_plural': 'Ubicaciones GPS',
                'ordering': ['-timestamp'],
            },
        ),
    ]
