# Generated by Django 6.1 on 2026-08-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivobiometrico',
            name='clave_api',
            field=models.CharField(blank=True, editable=False, help_text='Clave secreta generada automáticamente para autenticar a este dispositivo contra la API REST (header X-Device-Key).', max_length=64, unique=True),
        ),
    ]
