# Generated by Django 6.1 on 2026-08-24 05:05

import apps.incidencias.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave')], max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de incidencia',
                'verbose_name_plural': 'Tipos de incidencia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('estatus', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='incidencias/adjuntos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.incidencias.models.validar_tamano_adjunto])),
                ('persona_involucrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_involucrado', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='incidencias.tipoincidencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='incidencias.incidencia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de incidencia',
                'verbose_name_plural': 'Seguimientos de incidencia',
                'ordering': ['fecha'],
            },
        ),
    ]
