# Generated by Django 6.1 on 2026-08-24 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de despliegue (menor primero).')),
            ],
            options={
                'verbose_name': 'Nivel educativo',
                'verbose_name_plural': 'Niveles educativos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True, help_text='Ciclo en curso actualmente para este plantel.')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_escolares', to='core.plantel')),
            ],
            options={
                'verbose_name': 'Ciclo escolar',
                'verbose_name_plural': 'Ciclos escolares',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('plantel', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='CalendarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CLASES', 'Día de clases'), ('VACACIONES', 'Vacaciones'), ('EXAMEN', 'Periodo de exámenes'), ('SUSPENSION', 'Suspensión de labores'), ('INSCRIPCION', 'Periodo de inscripción/reinscripción'), ('OTRO', 'Otro')], max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío si es un evento de un solo día.', null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='academico.cicloescolar')),
            ],
            options={
                'verbose_name': 'Evento de calendario',
                'verbose_name_plural': 'Eventos de calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('clave', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('EN_LINEA', 'En línea'), ('MIXTA', 'Mixta')], default='PRESENCIAL', max_length=15)),
                ('duracion_periodos', models.PositiveSmallIntegerField(help_text='Número de periodos (semestres/cuatrimestres/años) del programa.')),
                ('titulo_otorga', models.CharField(blank=True, help_text='Título/grado que otorga al egresar.', max_length=150)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='academico.niveleducativo')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='core.plantel')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nivel__orden', 'nombre'],
                'unique_together': {('clave', 'plantel')},
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.CharField(help_text='Ej. "2024", "2024-2".', max_length=20)),
                ('total_creditos', models.PositiveSmallIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='academico.programa')),
            ],
            options={
                'verbose_name': 'Plan de estudios',
                'verbose_name_plural': 'Planes de estudio',
                'ordering': ['programa', '-version'],
                'unique_together': {('programa', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('clave', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('periodo', models.PositiveSmallIntegerField(help_text='Semestre/cuatrimestre dentro del plan al que pertenece.')),
                ('creditos', models.PositiveSmallIntegerField(default=0)),
                ('horas_teoricas', models.PositiveSmallIntegerField(default=0)),
                ('horas_practicas', models.PositiveSmallIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('OBLIGATORIA', 'Obligatoria'), ('OPTATIVA', 'Optativa')], default='OBLIGATORIA', max_length=15)),
                ('seriacion', models.ManyToManyField(blank=True, help_text='Materias que se requieren cursar/aprobar antes que esta.', related_name='materias_posteriores', to='academico.materia')),
                ('plan_estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.planestudios')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['plan_estudios', 'periodo', 'nombre'],
                'unique_together': {('plan_estudios', 'clave')},
            },
        ),
    ]
