# Generated by Django 6.1 on 2026-08-24 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Ej. "A", "B", "Único".', max_length=10)),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=30)),
                ('aula', models.CharField(blank=True, max_length=50)),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('MIXTO', 'Mixto')], default='MATUTINO', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.cicloescolar')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['ciclo_escolar', 'materia', 'clave'],
                'unique_together': {('ciclo_escolar', 'materia', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Horario de clase',
                'verbose_name_plural': 'Horarios de clase',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
