# Generated by Django 6.1 on 2026-08-24 04:59

import apps.nomina.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=10)),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Periodo de nómina',
                'verbose_name_plural': 'Periodos de nómina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='core.plantel')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['plantel', 'nombre'],
                'unique_together': {('plantel', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('nss', models.CharField(blank=True, max_length=15, verbose_name='NSS')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'rol_principal__in': ['DOCENTE', 'ADMINISTRATIVO']}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empleado', to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='nomina.puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ReciboNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percepciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('estatus_timbrado', models.CharField(choices=[('PENDIENTE', 'Pendiente de timbrar'), ('TIMBRADO', 'Timbrado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error de timbrado')], default='PENDIENTE', max_length=10)),
                ('uuid_cfdi', models.CharField(blank=True, max_length=36, verbose_name='UUID CFDI')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='nomina/cfdi/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml']), apps.nomina.models.validar_tamano_archivo_cfdi])),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='nomina/cfdi/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.nomina.models.validar_tamano_archivo_cfdi])),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='nomina.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='nomina.periodonomina')),
            ],
            options={
                'verbose_name': 'Recibo de nómina',
                'verbose_name_plural': 'Recibos de nómina',
                'ordering': ['-periodo', 'empleado'],
                'unique_together': {('empleado', 'periodo')},
            },
        ),
    ]
