# Generated by Django 6.1 on 2026-08-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada del plantel para calcular la geocerca de GPS.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantel',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada del plantel para calcular la geocerca de GPS.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantel',
            name='radio_geocerca_metros',
            field=models.PositiveIntegerField(default=150, help_text="Radio (metros) alrededor de latitud/longitud considerado 'dentro del plantel'."),
        ),
    ]
