# Generated by Django 6.1 on 2026-08-24 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_grupo_horarioclase'),
        ('alumnos', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150)),
                ('periodicidad', models.CharField(choices=[('UNICO', 'Pago único'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cobro', to='core.plantel')),
                ('programa', models.ForeignKey(blank=True, help_text='Vacío si el concepto aplica a todos los programas del plantel.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cobro', to='academico.programa')),
            ],
            options={
                'verbose_name': 'Concepto de cobro',
                'verbose_name_plural': 'Conceptos de cobro',
                'ordering': ['plantel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_etiqueta', models.CharField(blank=True, help_text='Ej. "Mensualidad 3/10", "Inscripción 2025-2026".', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_limite', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='alumnos.alumno')),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='academico.cicloescolar')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='finanzas.conceptocobro')),
            ],
            options={
                'verbose_name': 'Cargo de alumno',
                'verbose_name_plural': 'Cargos de alumnos',
                'ordering': ['-fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto fijo')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o monto fijo, según el tipo.', max_digits=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='alumnos.alumno')),
                ('concepto', models.ForeignKey(blank=True, help_text='Vacío si la beca aplica a todos los conceptos del alumno.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='becas', to='finanzas.conceptocobro')),
            ],
            options={
                'verbose_name': 'Beca / descuento',
                'verbose_name_plural': 'Becas / descuentos',
                'ordering': ['alumno'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque')], max_length=15)),
                ('origen', models.CharField(choices=[('MANUAL', 'Registro manual'), ('PASARELA', 'Pasarela de pago en línea')], default='MANUAL', max_length=10)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100)),
                ('capturado_por', models.ForeignKey(blank=True, help_text='Usuario administrativo que capturó el pago manual (vacío si vino de la pasarela).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_capturados', to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.cargoalumno')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
