# Generated by Django 6.1 on 2026-08-24 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_grupo_horarioclase'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('BAJA', 'Baja'), ('CONCLUIDO', 'Concluido')], default='INSCRITO', max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='alumnos.alumno')),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.cicloescolar')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.programa')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-ciclo_escolar', 'alumno'],
                'unique_together': {('alumno', 'ciclo_escolar')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('estatus', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('BAJA', 'Baja de la materia'), ('ACREDITADA', 'Acreditada'), ('NO_ACREDITADA', 'No acreditada')], default='INSCRITO', max_length=15)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_materia', to='academico.grupo')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='inscripciones.inscripcion')),
            ],
            options={
                'verbose_name': 'Inscripción a materia',
                'verbose_name_plural': 'Inscripciones a materias',
                'ordering': ['inscripcion', 'grupo'],
                'unique_together': {('inscripcion', 'grupo')},
            },
        ),
    ]
