# Generated by Django 6.1 on 2026-08-24 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_grupo_horarioclase'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=150)),
                ('nivel_estudios', models.CharField(blank=True, choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=15)),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('cedula_profesional', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('planteles', models.ManyToManyField(blank=True, related_name='docentes', to='core.plantel')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol_principal': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docente', to='academico.grupo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='docentes.docente')),
            ],
            options={
                'verbose_name': 'Asignación de docente',
                'verbose_name_plural': 'Asignaciones de docente',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
