# Generated by Django 6.1 on 2026-08-24 04:44

import apps.alumnos.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_grupo_horarioclase'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA_TEMPORAL', 'Baja temporal'), ('BAJA_DEFINITIVA', 'Baja definitiva'), ('EGRESADO', 'Egresado'), ('TITULADO', 'Titulado')], default='ACTIVO', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro')], max_length=1)),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=150)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('plan_estudios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='academico.planestudios')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='core.plantel')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='academico.programa')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol_principal': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AlumnoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR_LEGAL', 'Tutor legal'), ('OTRO', 'Otro')], max_length=15)),
                ('es_contacto_principal', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Relación alumno-tutor',
                'verbose_name_plural': 'Relaciones alumno-tutor',
            },
        ),
        migrations.CreateModel(
            name='DocumentoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ACTA_NACIMIENTO', 'Acta de nacimiento'), ('CURP', 'CURP'), ('COMPROBANTE_DOMICILIO', 'Comprobante de domicilio'), ('CERTIFICADO_ESTUDIOS', 'Certificado de estudios previos'), ('IDENTIFICACION', 'Identificación oficial'), ('FOTOGRAFIA', 'Fotografía'), ('OTRO', 'Otro')], max_length=25)),
                ('archivo', models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG. Máximo 5 MB.', upload_to='alumnos/documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.alumnos.models.validar_tamano_documento])),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Documento de alumno',
                'verbose_name_plural': 'Documentos de alumnos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('alumnos', models.ManyToManyField(related_name='tutores', through='alumnos.AlumnoTutor', to='alumnos.alumno')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol_principal': 'PADRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.AddField(
            model_name='alumnotutor',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.tutor'),
        ),
        migrations.CreateModel(
            name='Cardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('estatus', models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROBADA', 'Aprobada'), ('REPROBADA', 'Reprobada'), ('BAJA', 'Baja de la materia')], default='CURSANDO', max_length=15)),
                ('creditos_obtenidos', models.PositiveSmallIntegerField(default=0)),
                ('intento', models.PositiveSmallIntegerField(default=1, help_text='Número de vez que cursa la materia.')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardex', to='alumnos.alumno')),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardex', to='academico.cicloescolar')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardex', to='academico.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardex', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Registro de cardex',
                'verbose_name_plural': 'Cardex',
                'ordering': ['alumno', 'ciclo_escolar', 'materia'],
                'unique_together': {('alumno', 'materia', 'intento')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='alumnotutor',
            unique_together={('alumno', 'tutor')},
        ),
    ]
